---
title: "SoCal Data Science Bootcamp"
subtitle: "Summer 2023 Schedule"
format: 
  html:
    toc: true
    html-math-method: katex
    css: style.css
---

```{r}
#| echo: false

library(fontawesome)
```

## Before the Bootcamp

- **Sign up for GitHub** [`r fontawesome::fa(name = "link")`](https://github.com) Sign up for a free GitHub account if you don't already have one. Make sure to pick a username that you feel comfortable sharing on your CV. You will most likely use your GitHub username for many years in your data science career. Fill out [this survey](https://forms.gle/URiBx8mzoLt97n6e9) to let us know what your username is. Many of you have already done this.

- **Install R** [`r fontawesome::fa(name = "link")`](https://mirror.las.iastate.edu/CRAN/) Yes, you do need to download and install R even if you have downloaded before. There is a newer version.

- **Install RStudio** [`r fontawesome::fa(name = "link")`](https://posit.co/download/rstudio-desktop/) Yes, you do need to download and install RStudio even if you have downloaded before. There is a newer version. Download the free Desktop version.

- **Install and setup git** [`r fontawesome::fa(name = "video")`](https://uci.yuja.com/V/Video?v=7926437&node=33713927&a=41919805&autoplay=1) [`r fontawesome::fa(name = "chalkboard-teacher")`](https://socaldatascience.github.io/bootcamp-materials-2023/slides/day00-prep/00a-git-github-install.html)

- **Test your installations**  [`r fontawesome::fa(name = "video")`](https://uci.yuja.com/V/Video?v=7926702&node=33717865&a=36939698&autoplay=1)


## Day 1 - Introduction to the Toolkit

| Topic                         | Materials |
|-------------------------------|-----------|
|Meet & greet ||
| Introduction to Toolkit       |[`r fontawesome::fa(name = "desktop")`](slides/day01-eda/01a-intro-toolkit.html)           |
|Exploratory Data Analysis (EDA) Activity|`day01-eda-activity-username` repo on GitHub|


## Day 2 - Linear Regression and Model Evaluation


| Topic                         | Materials |
|-------------------------------|-----------|
| Simple Linear Regression   |[`r fontawesome::fa(name = "desktop")`](slides/day02-regression/02a-regression.html)           |
|Regression Activity|`day02-regression-activity-username` repo on GitHub|

## Day 3 - Categorical Data Analysis

| Topic                         | Materials |
|-------------------------------|-----------|
| Categorical Data Analysis |[`r fontawesome::fa(name = "desktop")`](slides/day03-cda/03a-cda.html)           |
|Categorical Data Analysis Activity|`day03-cda-activity-username` repo on GitHub|


## Day 4 - Generalized Linear Models



| Topic                         | Material |
|-------------------------------|-----------|
| Logistics Regression     |[`r fontawesome::fa(name = "desktop")`](slides/day04-glm/04a-logistic-regression.html)           |
| Logistics Regression Activity    |`day04-logistic-activity-username` repo on GitHub              |
| Good Workflow Practices      |[`r fontawesome::fa(name = "desktop")`](slides/day04-glm/04b-workflow.html)           |
| Learn to Collaborate on GitHub Activity       |`day04-collaborate-teamnumber` repo on GitHub           |



## Day 5 - Hierarchical Linear Models

| Topic                         | Material |
|-------------------------------|-----------|
| Hierarchical Linear Models without Predictors     |[`r fontawesome::fa(name = "desktop")`](slides/day05-lme/05a-hlm-nopred.html)           |
| Hierarchical Linear Models Notes    |`day05-hlm-username` repo on GitHub              |
| Hierarchical Linear Models with Predictors      |[`r fontawesome::fa(name = "desktop")`](slides/day05-lme/05a-hlm-pred.html)           |
