---
title: "Linear Regression"
author: "Created Dr. Mine Dogucu and Presented by Dr. Jaynes"
format: 
  revealjs:
    slide-number: true
    logo: "https://socaldatascience.github.io/bootcamp-materials-2022/img/socalds-logo.png"
    theme: ["slide-style.scss"]
    incremental: false
---


## Goals
- Review Linear Regression Concepts from your Data Science Courses 
- Conditions for Least Squares Regression and Diagnostics
- Multiple Linear Regression
- Model Evaluation 


```{r echo = FALSE, message = FALSE}
library(tidyverse)
library(openintro)
library(broom)
theme_set(theme_gray(base_size = 18))
```





<!--

## Data `babies` in `openintro` package

```{r echo = FALSE}


glimpse(babies)

```

##  Baby Weights
:::: {.columns}
::: {.column width="40%"}
```{r eval = FALSE, fig.align='center', message = FALSE, warning = FALSE}
ggplot(babies, 
       aes(x = gestation, y = bwt)) +
  geom_point()

```
:::

::: {.column width="60%"}
```{r echo = FALSE, fig.align='center', message = FALSE, fig.height= 6,warning = FALSE}


ggplot(babies, 
       aes(x = gestation, y = bwt)) +
  geom_point()

```
:::
::::

## Response and Explanatory Variables

| Variable    | Variable Name | Type of Variable |
|-------------|-----------------|---------|
| Response (y)    | Birth weight | Numeric |
| Explanatory (x) | Gestation           | Numeric |


## Insert Mine's UCI ICS 80 Sampling and Study Design (i.e. regression slides)

## Insert Mine's UCI STATS 115 Evaluating Regression Models
-->
